# Syfony2 framework
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
#        hinclude_default_template: 'SaseSharedBundle::hinclude.html.twig'
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  snc_redis.session.handler # session.handler.native_file
        name: "ILCITTOOL"
        cookie_lifetime: 2592000
        cookie_domain: ".%domain_com_ilcfrance_ittool%"
        gc_probability: 0
        gc_maxlifetime: 2592000
    fragments: { path: /_fragment }
    http_method_override: true
    assets: ~
    cache:
        app: cache.adapter.redis
    php_errors:
        log: true