security:
    access_denied_url:    ~ # Example: /foo/error403
    # strategy can be: none, migrate, invalidate
    session_fixation_strategy:  invalidate
    hide_user_not_found:  true
    always_authenticate_before_granting:  false
    erase_credentials:    true
    access_decision_manager:
        strategy:             affirmative # One of affirmative, consensus, unanimous
        allow_if_all_abstain:  false
        allow_if_equal_granted_denied:  true
    encoders:
        ILC\DataBundle\Entity\Administrator:
            algorithm: sha512
            iterations: 10
    providers:
        user_provider:
            entity:
                class: "ILCDataBundle:Administrator"

        chain_provider:
            chain:
                providers: ["user_provider"]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt))/
            security: false
            anonymous:  true
        resources:
            pattern:  ^/(bundles|res)/
            security: false
            anonymous:  true
        secoff:
            pattern:  ^/(login|login_check|logout)/
            security: false
            anonymous:  true
        main:
            pattern:      .*
            provider: chain_provider
            form_login:
                check_path:     _security_check
                login_path:     _security_login
                use_forward:    false
                always_use_default_target_path: false
                default_target_path: /
                target_path_parameter:  "LoginForm[target_path]"
                use_referer:    true
                username_parameter:     "LoginForm[username]"
                password_parameter:     "LoginForm[password]"
                post_only:      true
                remember_me:    false
                require_previous_session: false
                
            logout:
                path:   _security_logout
                invalidate_session: false
                
            security: true
            anonymous:    true
    access_control:
        - { path: ^/_wdt/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bundles/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/res/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, roles: IS_AUTHENTICATED_FULLY }
    access_denied_url: /
