# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
#    form_themes:
#        - 'SaseSharedBundle::form.html.twig'
    globals:
        scheme: "%scheme%"
        domain_com_ilcfrance_ittool: "%domain_com_ilcfrance_ittool%" 
        timezone:               "Europe/Paris"
        default_locale: "%locale%"
    paths:
        '%kernel.root_dir%/../web/res': public_res