<?php
namespace ILC\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleformationRepository
 * This class was generated by the Doctrine ORM.
 * Add your own custom
 * repository methods below.
 */
class ModuleformationRepository extends EntityRepository
{

	public function getAllQuery($cache = true)
	{
		$dql = 'SELECT m FROM ILC\DataBundle\Entity\Moduleformation m ';
		$query = $this->getEntityManager()->createQuery($dql);
		if ($cache) {
			$query->setCacheable('true')->useQueryCache(true)->setLifetime(60)->useResultCache(true, 60);
		}
		return $query;
	}

	public function getAll($cache = true)
	{
		$query = $this->getAllQuery($cache);
		return $query->getResult();
	}
}
