<?php
namespace ILC\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModulepreinscriptionRepository
 * This class was generated by the Doctrine ORM.
 * Add your own custom
 * repository methods below.
 */
class ModulepreinscriptionRepository extends EntityRepository
{
}