<?php
namespace ILC\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SessioninscriptionRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessioninscriptionRepository extends EntityRepository
{
}
